site_name: Mason's Ansible Docs
repo_url: https://github.com/mfeuhrer/ansible
edit_uri: blob/main/docs
theme:
  name: material
  palette:
    primary: deep_orange
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
markdown_extensions:
  - smarty: {}
  - sane_lists : {}
  - footnotes: {}
  # - toc:
    #  baselevel: 1
nav:
  - Home: README.md
  - Quick Start: quick-start.md
  - Playbooks:
    - linux-updates: playbooks/linux-updates.md
    - linux-common: playbooks/linux-common.md
    - apt-common: playbooks/apt-common.md
    - apt-proxguest: playbooks/apt-proxguest.md
    - apt-containerhosts: playbooks/apt-containerhosts.md
  - References:
    - ansible.cfg: ansible.cfg.md
    - Inventory File: inventory.md