---
# a lot of it came from here: https://pastebin.com/rPiqt8q6
- hosts: linux
  become: yes
  vars:
    hostname: "{{ inventory_hostname }}" # Hostname from Ansible inventory name
  tasks:
  - name: Create SNMP Config Folder
    ansible.builtin.file:
      path: /etc/snmp
      state: directory
  - name: Configure OS Update SNMP Module
    get_url:
      url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/osupdate
      dest: /etc/snmp/osupdate
      mode: 0755
      # 755 allows all to execute
  - name: Configure DistroWatch SNMP Module
    get_url:
      url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
      dest: /usr/bin/distro
      mode: 0755
- hosts: apt
  become: yes
  vars:
    hostname: "{{ inventory_hostname }}" # Hostname from Ansible inventory name
  tasks:
  - name: Install Required Packages
    apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
        - ufw
        - snmpd
        - htop
        - git
      state: latest
      update_cache: true
      autoclean: true
      autoremove: true
  - name: Remove Unwanted Packages
    apt:
      name:
        - netadata
        - wazuh-agent
        - landscape-client
      state: absent
      autoclean: true
      autoremove: true
  - name: Configure Systemd SNMP Module
    copy:
      src: ../resources/systemd.py
      dest: /etc/snmp/systemd.py
      mode: 0755
  - name: Configure Systemd Extended SNMP Module 
    copy:
      src: ../resources/systemd.json
      dest: /etc/snmp/systemd.json
- hosts: vps:!containerhosts
  become: yes
  vars:
    hostname: "{{ inventory_hostname }}" # Hostname from Ansible inventory name
  tasks:
  - name: Configure SNMP
    template: src=../resources/snmpd.conf.d/vps.conf dest=/etc/snmp/snmpd.conf
    register: snmp_config_updated
  - name: Restart SNMP
    service:
      name: snmpd
      state: restarted
    when: snmp_config_updated.changed
- hosts:
  - linux:!vps
  - linux:!containerhosts
  become: yes
  vars:
    hostname: "{{ inventory_hostname }}" # Hostname from Ansible inventory name
  tasks:
  - name: Configure SNMP
    template: src=../resources/snmpd.conf.d/snmpd.conf dest=/etc/snmp/snmpd.conf
    register: snmp_config_updated
  - name: Restart SNMP
    service:
      name: snmpd
      state: restarted
    when: snmp_config_updated.changed