- hosts: linux
  # become: yes
  vars:
    hostname: "{{ inventory_hostname }}" # Hostname from Ansible inventory name
  tasks:
    - name: Call webhook
      ansible.builtin.uri:
        url: ""
        method: POST
        body_format: json
        body: {
          message: "I sure hope this works!",
          hostname: "{{ hostname }}",
          timestamp: "{{ ansible_date_time.iso8601 }}",
          ansible_version: "{{ ansible_version.full }}",
          ansible_distribution: "{{ ansible_distribution }}"
        }
        headers:
          Content-Type: "application/json"
          X-Webhook-Key: "{{ lookup('env', 'webhook_key') }}"

      register: webhook_response

    - name: Show webhook response
      ansible.builtin.debug:
        var: webhook_response