- hosts: proxmox
  vars:
    hostname: "{{ inventory_hostname }}" # Hostname from Ansible inventory name
  tasks:
  - name: Install Checkmk Agent
    apt:
      deb: https://omd.omicr0n.com/omicr0n/check_mk/agents/check-mk-agent_2.4.0p12-1_all.deb
  - name: Apt Update Plugin
    get_url:
        url: https://omd.omicr0n.com/omicr0n/check_mk/agents/plugins/mk_apt
        dest:  /usr/lib/check_mk_agent/plugins/mk_apt
        mode: 0755
  - name: Login Plugin
    get_url:
        url: https://omd.omicr0n.com/omicr0n/check_mk/agents/plugins/mk_logins
        dest:  /usr/lib/check_mk_agent/plugins/mk_logins
        mode: 0755
  - name: SMART plugin
    get_url:
        url: https://omd.omicr0n.com/omicr0n/check_mk/agents/plugins/smart
        dest:  /usr/lib/check_mk_agent/plugins/smart
        mode: 0755
  - name: lvm Plugin
    get_url:
        url: https://omd.omicr0n.com/omicr0n/check_mk/agents/plugins/lvm
        dest:  /usr/lib/check_mk_agent/plugins/lvm
        mode: 0755
  - name: sshd_config Plugin
    get_url:
        url: https://omd.omicr0n.com/omicr0n/check_mk/agents/plugins/mk_sshd_config
        dest:  /usr/lib/check_mk_agent/plugins/mk_sshd_config
        mode: 0755
  - name: dnsclient Plugin
    get_url:
        url: https://omd.omicr0n.com/omicr0n/check_mk/agents/plugins/dnsclient
        dest:  /usr/lib/check_mk_agent/plugins/dnsclient.py
        mode: 0755
  - name: dnsclient Plugin Config
    copy:
      src: ../resources/checkmk/dnsclient.cfg
      dest: /etc/check_mk/dnsclient.cfg
      mode: 0755